### ISSUE TITLE
MouseLook2d isn't compatible with Unity 4, needs moving to Unity 5 rep

### ISSUE THREAD

**Issue by jeanfabre** [jeanfabre/PlayMakerCustomActions_U4#4]
https://github.com/jeanfabre/PlayMakerCustomActions_U4/commit/885955dcc10d2862a55126f9c6905cb9b3698bf8

**Comment by djaydino** [comment]
where can i find Unity 5 rep?

**Comment by djaydino** [comment]
Moved to U5
