### ISSUE TITLE
Invalid cast exception

### ISSUE THREAD

**Issue by Reignman75** [jeanfabre/PlayMakerCustomActions_U4#5]
I cannot add the action 'Set Animator Float' to state in Playmaker. When doing so I get an invalid cast exception.
Not sure this is a Playmaker issue but I only get this issue using the Animator actions from Animator Proxy. All the rest is doing fine.
Using Unity version 5.4.0f3

![invalidcastexception](https://cloud.githubusercontent.com/assets/23666569/20543324/f5169ede-b105-11e6-83fb-d91f5e25009b.PNG)

Hope someone can help me out to solve this problem.

**Update**
I only get this fault message when trying to select the 'set animator bool - float and int' actions. I cannot actually select the action to add it in the state. The action browser empties out. 

**Update 2**
Found the problem. I had to tick off the preview in the action browser. :-|

Rob

**Comment by djaydino** [comment]
Great, i will close this issue. i believe that you can also preview now without an issue.
