### ISSUE TITLE
AudioPlayAdvanced not compatible with Unity 4

### ISSUE THREAD

**Issue by jeanfabre** [jeanfabre/PlayMakerCustomActions_U4#6]
Hi,

It's important to always verify that actions are working inside Unity 4 for this repository, I corrected AudioPlayAdvanced as is featured api that only works on Unity 5 ( I think 5.5). So Please double check that these 5 only api works properly, maybe 5.3 is fine or even 5.0.

 Bye,

 Jean

**Comment by djaydino** [comment]
sorry it was mend to be in U5, i placed it in the wrong folder :)
thx for editing.
