### ISSUE TITLE
ugui actions should go in the dedicated Rep, so that they can be included in the full package too

### ISSUE THREAD

**Issue by jeanfabre** [jeanfabre/PlayMakerCustomActions_U4#7]
Hi,

 I saw you added Assets/PlayMaker Custom Actions/uGui/uGuiImageGetFillAmount.cs

but really, it would be best to put it in  https://github.com/jeanfabre/PlayMaker--Unity--UI/tree/master/Assets/PlayMaker%20Custom%20Actions/uGui

Then, when I make a new build for the packages, it will be included.

 Bye,

 Jean

**Comment by djaydino** [comment]
Only saw the comment now :)
i have moved them to the Unity--UI
